version: 0.2
phases:
  build:
    commands:
      - python -m pip install -r build_requirements.txt
      - python -m pip install spin
      - git submodule update --init
      - python -m spin build -- -Dallow-noblas=true
